# Generated by Django 4.2.2 on 2023-06-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver_app', '0003_monthlycumulative_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycumulative',
            name='day',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
