# Generated by Django 4.2.2 on 2023-06-12 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver_app', '0004_dailycumulative_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 12, 12, 23, 2, 341265, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
