# Generated by Django 4.2.2 on 2023-06-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver_app', '0008_alter_delivery_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
