# Generated by Django 4.2.2 on 2023-06-12 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver_app', '0014_alter_delivery_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivered',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
