# Generated by Django 4.2.2 on 2023-06-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver_app', '0015_alter_delivery_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
